version: "3.8"

services:
  ensib-monuments:
    container_name: ensib-monuments
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
        DATABASE_URL: ${DATABASE_URL}
    environment:
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ensib_next_cache:/app/.next/cache
    restart: always

  postgres:
    container_name: ensib-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: monuments
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - ensib-network
    command: pnpm exec prisma migrate deploy
    stdin_open: true
    tty: true

volumes:
  ensib_next_cache:
    name: ensib-next-cache-volume
  pgdata:
    name: ensib-pgdata-volume

networks:
  ensib-network:
    name: ensib-network
